
server:
  port: 8090

spring:
  datasource:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:h2:mem:h2test
    driver-class-name: org.h2.Driver
    username: root
    password: test